### ISSUE TITLE
Some games won't run correctly

### ISSUE THREAD

**Issue by berkaykarlik** [berkaykarlik/CHIP-8-interpreter#3]
roms\chip8Archive\roms\br8kout.ch8:
```
Traceback (most recent call last):
  File "C:\Users\Msi\Desktop\myProjects\CHIP-8\main.py", line 168, in <module>
    main(args.rom_path[0])
  File "C:\Users\Msi\Desktop\myProjects\CHIP-8\main.py", line 132, in main
    processor.dxyn(reg, mem, gui, nd_nimble, rd_nimble, th_nimble)
  File "C:\Users\Msi\Desktop\myProjects\CHIP-8\modules\processor.py", line 244, in dxyn
    is_flipped = gui.set(x+i, y+j)
  File "C:\Users\Msi\Desktop\myProjects\CHIP-8\modules\gui.py", line 56, in set
    val = self.__frame[x][y]
IndexError: index 64 is out of bounds for axis 0 with size 64
```

roms\chip8Archive\roms\flightrunner.ch8:
```
Traceback (most recent call last):
  File "C:\Users\Msi\Desktop\myProjects\CHIP-8\main.py", line 168, in <module>
    main(args.rom_path[0])
  File "C:\Users\Msi\Desktop\myProjects\CHIP-8\main.py", line 74, in main
    curr_instr = mem.fetch()
  File "C:\Users\Msi\Desktop\myProjects\CHIP-8\modules\memory.py", line 71, in fetch
    first_byte = int(self.__memory[self.__pc])
IndexError: index 4096 is out of bounds for axis 0 with size 4096
```

more can be added as I discover them.

**Comment by berkaykarlik** [comment]
breakthrough is fixed as a side product of #6. 
Flightrunner is  still same.

**Comment by berkaykarlik** [comment]
David winter's games work just fine. chip8archieve is usually problematic. Maybe they expect different chip-8 spesifications. To be investigated.

**Comment by berkaykarlik** [comment]
after finding this [test suite](https://github.com/berkaykarlik/Chip8py/blob/main/roms/chip8-test-suite.ch8) and fixing some implementation specific quirks, david winter's game got broken in various ways as well. All test passes yet no games work. I'm starting to regret this project all together.

**Comment by berkaykarlik** [comment]
Lets just assume they are written for different chip8 versions. I don't have a way to distinguish. So don't care about this issue anymore.
